"use client";
import "@/styles/globals.css";
import vazirFont from "@/constants/localFont";
import { Toaster } from "react-hot-toast";

import Providers from "@/providers/providers";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={`${vazirFont.variable}  font-sans `}>
        <Providers>
          <Toaster />
          <div className="xl:max-w-screen-xl container">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
