import "@/styles/globals.css";
import vazirFont from "@/constants/localFont";
import Header from "./_components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={`${vazirFont.variable}  font-sans `}>
        <Header />
        <div className="xl:max-w-screen-xl container">{children}</div>
      </body>
    </html>
  );
}
